name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6634e741585109fd9693e1c5ecb6d0e0464be482e432b8c22ba8b9510e2a5859"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
