name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0728cfb59a629cbeebc996f76c44ad42e58780933c0de4062257030faaabaf4b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
