name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0e30e058192b225e2470e3e81e6283d61ab2b50410e7f3ce8eb59ebc197862d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
